###################################################################################
### Web服务器配置
###################################################################################
server:
  port: 18081
  servlet:
    context-path: /

###################################################################################
### logging(logback)
###################################################################################
logging:
  config: classpath:logback.xml
  level:
    org.springframework: warn
    org.clever: debug
    org.clever.canal: info

###################################################################################
### Spring配置
###################################################################################
spring:
  profiles.active: dev
  application.name: clever-nashorn-server
  aop.proxy-target-class: true

  servlet: #------------------------------------------------------------ 文件上传配置
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: 'data/temp'

  http: #------------------------------------------------------------------ http配置
    converters:
      preferred-json-mapper: jackson
    encoding:
      charset: UTF-8
      force: true

  jackson: #------------------------------------------------------------ jackson配置
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8

  resources: #------------------------------------------------ html、js、css 静态资源
    chain:
      cache: false
      compressed: true
    cache:
      period: 0s
    static-locations: ['classpath:/static/']

  redis: #---------------------------------------------------------------- Redis配置
    ssl: false
    host: redis.msvc.top
    port: 6379
    timeout: 10s
    database: 0
    password: lizhiwei1993
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 1
        max-wait: 1s
      shutdown-timeout: 1000ms

  datasource: #----------------------------------------------------------- 数据库配置
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.4.9.161:3306/web-exchange-nashorn?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&dataBaseType=write
    username: b2b_5
    password: KgSYtPKRF6Lx
    hikari:
      pool-name: defaultDataSource
      data-source-properties:
        serverTimezone: GMT+8
        useUnicode: true
        characterEncoding: utf-8
        zeroDateTimeBehavior: convert_to_null
        useSSL: false
      auto-commit: false
      maximum-pool-size: 100
      minimum-idle: 5
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  elasticsearch:
    jest:
      uris: http://10.4.9.30:9200
      multi-threaded: true
      connection-timeout: 30s
      read-timeout: 300s

  cloud: #------------------------------------------------------------ Spring Cloud
    consul:
      enabled: false
      host: consul.msvc.top
      port: 80
      discovery:
        enabled: true
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        instance-zone: wuhan
        instance-group: svc
        tags:
          - serviceName=${spring.application.name}
        health-check-path: '/actuator/health'
        health-check-interval: 1s
        prefer-ip-address: true
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health

###################################################################################
### management配置
###################################################################################
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - health
          - info
          - env
          - metrics
          - prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    enable:
      root: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: 5s
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.75, 0.9, 0.95, 0.99
      sla:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 500ms, 1s, 2s, 3s, 4s, 5s, 10s, 15s, 20s, 30s, 50s

###################################################################################
### mybatis-plus配置
###################################################################################
mybatis-plus:
  configuration:
    auto-mapping-behavior: partial
    auto-mapping-unknown-column-behavior: none
    map-underscore-to-camel-case: true
  mapper-locations: 'classpath*: **/*.xml'
  check-config-location: true
  executor-type: reuse
  global-config:
    banner: true
    db-config:
      id-type: auto
      select-strategy: not_null
      insert-strategy: not_null
      update-strategy: not_null

###################################################################################
### clever security配置
###################################################################################
clever:

  nashorn:
    config:
      multiple-data-source:
        default-data-source: data-source-b2b-test
        data-source-global-config:
          pool-name: defaultDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          data-source-properties:
            serverTimezone: GMT+8
            useUnicode: true
            characterEncoding: utf-8
            zeroDateTimeBehavior: convert_to_null
            useSSL: false
          auto-commit: true
          maximum-pool-size: 20
          minimum-idle: 1
          max-lifetime: 1800000
        data-source-map:
          b2b-test:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://10.4.9.161:3306/b2b5?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&dataBaseType=write
            username: b2b_5
            password: KgSYtPKRF6Lx
          b2b-prod-ro:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://b2b5-cluster.cluster-ro-c9xmug6pfqr3.rds.cn-northwest-1.amazonaws.com.cn:3306/b2b5?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&dataBaseType=write
            username: user_b2b5
            password: Dw6-Yc3-coD-q2O
          b2b-local-validate:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://jzterp.cluster-c9xmug6pfqr3.rds.cn-northwest-1.amazonaws.com.cn/jzterp?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&dataBaseType=write
            username: jzterp
            password: NC4JSmEbJ6mDaLp9pG
          erp-hb:
            driver-class-name: oracle.jdbc.driver.OracleDriver
            jdbc-url: jdbc:oracle:thin:@10.3.4.30:1521:branch
            username: viewer
            password: viewer
          erp-cq:
            driver-class-name: oracle.jdbc.driver.OracleDriver
            jdbc-url: jdbc:oracle:thin:@10.61.9.12:1521:branch
            username: viewer
            password: viewer
#          erp-hn:
#            driver-class-name: oracle.jdbc.driver.OracleDriver
#            jdbc-url: jdbc:oracle:thin:@10.36.5.90:1521:branch
#            username: viewer
#            password: viewer
      multiple-jest:
        default-jest: jest1
        global-config:
          multi-threaded: true
          connection-timeout: 10s
          read-timeout: 600s
        jest-config-map:
          b2b-test-es:
            uris: http://10.4.9.30:9200
            connection-timeout: 10s
            read-timeout: 600s
          b2b-prod-es:
            uris: http://10.161.0.26:9200,http://10.161.1.26:9200
            connection-timeout: 10s
            read-timeout: 600s
